#!/bin/bash

#sudo apt update

download_url="https://launcher.mojang.com/v1/objects/a412fd69db1f81db3f511c1463fd304675244077/server.jar"
minecraft_server_file_name="server.jar"
installation_path="~/minecraft"

function install_java {
  sudo apt install default-jre -y
}

function install_minecraft_server {
  if [ -f $minecraft_server_file_name ]; then
    echo "Already downloaded minecraft server"
  else
    wget $download_url
  fi
}

function install_beautifier_prerequisites {
  sudo apt install bc -y
}

function run_minecraft_server {
  ./run $minecraft_server_file_name
}

function agree_to_eula {
  sed -i 's/eula=false/eula=true/' eula.txt
}

function uninstall {
  rm -rf eula.txt logs/ server.jar server.properties
}

function create_install_dir {
  if [ -d $installation_path ]; then
    mkdir $installation_path
  fi
  pushd .
  cd $installation_path
}

install_beautifier_prerequisites
. ./beautifier

run_action create_install_dir
run_action install_java
run_action install_minecraft_server
run_action run_minecraft_server
run_action agree_to_eula
run_action run_minecraft_server
#run_action uninstall
