#!/bin/bash

download_url="https://launcher.mojang.com/v1/objects/a412fd69db1f81db3f511c1463fd304675244077/server.jar"
minecraft_server_file_name="server.jar"

function install_java {
  sudo apt install default-jre -y
}

function install_minecraft_server {
  if [ -f $minecraft_server_file_name ]; then
    echo "Already downloaded minecraft server"
  else
    wget $download_url
  fi
}

function install_beautifier_prerequisites {
  sudo apt install bc -y
}

function run_minecraft_server {
  ./scripts/run_in_tmux_session
  ./scripts/view_running_tmux_session
}

function agree_to_eula {
  eula_path="eula.txt"

  if [ -f $eula_path ]; then
    sed -i 's/eula=false/eula=true/' $eula_path
    echo "eula=true" > $eula_path
  else
    sed -i 's/eula=false/eula=true/' $eula_path
  fi
}

function log_pwd {
  echo "$(pwd)"
}

install_beautifier_prerequisites
. ./scripts/beautifier

run_action install_java
run_action install_minecraft_server
run_action agree_to_eula
run_minecraft_server
