#!/bin/bash

. ./scripts/beautifier

session_name="minecraft"

sessions=$(tmux ls)
echo $sessions

if [[ $sessions == *"$session_name"* ]]; then
  tmux a -t $session_name
else
  log_info "Running minecraft in tmux session '$session_name'\n"
  tmux new -s $session_name -d ./scripts/run
fi
