#!/bin/bash

. ./scripts/beautifier

sudo echo "a prompt for sudo" >/dev/null
run_action "sudo cp ./scripts/init.d.script /etc/init.d/minecraft"
run_action "sudo update-rc.d minecraft defaults"

#sudo cp ./scripts/init.d.script /etc/init.d/minecraft
#sudo update-rc.d minecraft defaults
