#!/bin/bash

. ./scripts/beautifier

session_name="minecraft"

if [[ $(sudo -u admin tmux ls) == *"$session_name"* ]]; then
  tmux a -t $session_name
else
  log_info "Running minecraft in tmux session '$session_name'\n"
  run_action "sudo -u admin tmux new -s $session_name -d ./scripts/run"
fi
