#!/bin/bash

. ./scripts/beautifier

session_name="minecraft"

if [[ $(sudo -u admin tmux ls) == *"$session_name"* ]]; then
  run_action 'sudo -u admin tmux send-keys -t $session_name.0 "stop" ENTER'
else
  log_info "Minecraft server is not running\n"
fi

while [[ $(sudo -u admin tmux ls) == *"$session_name"* ]]
do
  log_info "Waiting for minecraft server to stop...\n"
  sleep 0.5
done
log_success "Minecraft server has stopped\n"
