#!/bin/bash

. ./scripts/beautifier

session_name="minecraft"

if [[ $(tmux ls) == *"$session_name"* ]]; then
  tmux a -t $session_name
else
  log_failure "The server is not running in the tmux session '$session_name'\n"
  exit 3
fi

